version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: save-restricted-bot
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - TOKEN=${TOKEN}
      - ID=${ID}
      - HASH=${HASH}
      - STRING=${STRING}
      - DATA_DIR=/app/data
      - TZ=Asia/Shanghai
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
      - session-data:/app/session-storage

volumes:
  session-data:
